# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
source 'https://mirrors.tuna.tsinghua.edu.cn/git/CocoaPods/Specs.git'

target 'SynchronizedCapture' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SynchronizedCapture
   # pod 'SwiftSocket', :git => 'https://github.com/swiftsocket/SwiftSocket.git', :branch => 'master'
    pod 'SwiftCollections'
    pod 'BlueSocket'

  target 'SynchronizedCaptureTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SynchronizedCaptureUITests' do
    # Pods for testing
  end

end

